import { Scheduler } from './scheduler.js'
import type { JobDefinition, JobExpression, JobHandler, JobId, JobOptions } from './types.js'

export { Scheduler }
export { ScheduleJobRunner } from './runner.js'
export type {
  DistributedJobOptions,
  JobDefinition,
  JobExpression,
  JobHandler,
  JobId,
  JobInfo,
  JobOptions,
  JobRunInfo,
} from './types.js'

let _jobId = 1

export function defineJob<TId extends JobId>(
  id: TId,
  expression: JobExpression,
  handler: JobHandler,
  options?: JobOptions,
): JobDefinition<TId>
export function defineJob(
  expression: JobExpression,
  handler: JobHandler,
  options?: JobOptions,
): JobDefinition<number>
export function defineJob(
  idOrExpression: JobId | JobExpression,
  expressionOrHandler: JobExpression | JobHandler,
  handlerOrOptions?: JobHandler | JobOptions,
  maybeOptions?: JobOptions,
): JobDefinition {
  if (typeof expressionOrHandler === 'function') {
    return {
      id: _jobId++,
      idAutoGenerated: true,
      type: 'job',
      expression: idOrExpression as JobExpression,
      handler: expressionOrHandler,
      options: handlerOrOptions as JobOptions | undefined,
    }
  }

  if (typeof handlerOrOptions !== 'function') {
    throw new TypeError('defineJob handler is required')
  }

  return {
    id: idOrExpression as JobId,
    type: 'job',
    expression: expressionOrHandler,
    handler: handlerOrOptions,
    options: maybeOptions,
  }
}
