import { scheduleJob, Job as NSJob } from 'node-schedule'
import { pathToFileURL } from 'node:url'
import type { JobHandler, JobDefinition, JobInfo, JobOptions } from './types.js'
import { ScheduleJobRunner } from './runner.js'
import { scanDirectory, type ScannedFile } from '@hile/loader'

export class Scheduler {
  private jobs = new Map<string, NSJob>()
  private meta = new Map<string, { type: 'cron' | 'delay'; expression: string }>()

  add(id: string | number, expression: string, handler: JobHandler, options?: JobOptions): void
  add(id: string | number, options: { delay: number }, handler: JobHandler, jobOptions?: JobOptions): void
  add(
    id: string | number,
    exprOrOpts: string | { delay: number },
    handler: JobHandler,
    options?: JobOptions,
  ): void {
    const key = String(id)
    if (this.jobs.has(key)) throw new Error(`Job "${key}" already exists`)

    if (typeof exprOrOpts === 'string') {
      const info = { id: key, type: 'cron' as const, expression: exprOrOpts }
      const safeHandler = new ScheduleJobRunner(options).createHandler(handler, info)
      const job = scheduleJob(exprOrOpts, safeHandler)
      if (!job) throw new Error(`Failed to schedule job "${key}" with expression "${exprOrOpts}"`)
      this.jobs.set(key, job)
      this.meta.set(key, { type: info.type, expression: info.expression })
    } else {
      const date = new Date(Date.now() + exprOrOpts.delay)
      const info = { id: key, type: 'delay' as const, expression: `delay:${exprOrOpts.delay}` }
      const safeHandler = new ScheduleJobRunner(options).createHandler(handler, info)
      const job = scheduleJob(date, safeHandler)
      if (!job) throw new Error(`Failed to schedule job "${key}" with delay ${exprOrOpts.delay}`)
      this.jobs.set(key, job)
      this.meta.set(key, { type: info.type, expression: info.expression })
    }
  }

  remove(id: string | number): void {
    const key = String(id)
    const job = this.jobs.get(key)
    if (job) {
      job.cancel()
      this.jobs.delete(key)
      this.meta.delete(key)
    }
  }

  stop(): void {
    for (const job of this.jobs.values()) {
      job.cancel()
    }
    this.jobs.clear()
    this.meta.clear()
  }

  getJobs(): JobInfo[] {
    return Array.from(this.meta.entries()).map(([id, m]) => ({
      id,
      type: m.type,
      expression: m.expression,
    }))
  }

  /**
   * 从目录自动加载 schedule 任务文件
   * 文件后缀: {suffix}.ts/.js，default export 须为 defineJob 返回值
   * @param directory 目录路径
   * @param options.suffix 文件后缀标记，默认 'schedule'
   * @returns 注销函数
   */
  async load(directory: string, options?: { suffix?: string }): Promise<() => void> {
    const files = await scanDirectory(directory, { suffix: options?.suffix || 'schedule' })
    const offFns: (() => void)[] = []

    try {
      for (const file of files) {
        const mod: { default?: JobDefinition } = await import(pathToFileURL(file.absolute).href)
        const jobDef = mod.default
        if (!jobDef || jobDef.type !== 'job') continue

        const key = this.resolveLoadedJobId(jobDef, file)
        if (typeof jobDef.expression === 'string') {
          this.add(key, jobDef.expression, jobDef.handler, jobDef.options)
        } else {
          this.add(key, jobDef.expression, jobDef.handler, jobDef.options)
        }
        offFns.push(() => this.remove(key))
      }
    } catch (error) {
      for (const off of offFns.reverse()) off()
      throw error
    }

    return () => {
      for (const off of offFns) off()
    }
  }

  private resolveLoadedJobId(jobDef: JobDefinition, file: ScannedFile): string {
    return jobDef.idAutoGenerated ? file.routePath : String(jobDef.id)
  }
}
