import type { RedisLockLike, WithLockOptions } from '@hile/redis-lock'

export type JobRunInfo = {
  id: string
  type: 'cron' | 'delay'
  expression: string
}

export type JobInfo = JobRunInfo

export type JobHandler = (info: JobRunInfo) => Promise<void> | void
export type JobId = string | number
export type JobExpression = string | { delay: number }

export type DistributedJobOptions = {
  redis: RedisLockLike
  ttl: number
  namespace?: string
  lockKey?: string | ((info: JobRunInfo) => string)
  policy?: 'skip-if-locked' | 'wait'
  wait?: number
  pollInterval?: number
  maxPollInterval?: number
  renew?: WithLockOptions['renew']
}

export type JobOptions = {
  distributed?: DistributedJobOptions
  onError?: (error: unknown, info: JobRunInfo) => Promise<void> | void
  onSkip?: (info: JobRunInfo) => Promise<void> | void
}

export type JobDefinition<TId extends JobId = JobId> = {
  id: TId
  idAutoGenerated?: boolean
  type: 'job'
  expression: JobExpression
  handler: JobHandler
  options?: JobOptions
}
